spring:
  application:
    name: msa
  mail:
    host: smtp.gmail.com
    port: 587
    username: preejer8013@gmail.com
    password: mvep okhv abar kkmx
    properties:
      mail:
        smtp:
          starttls:
            enable: true

          auth: true

secret:
  key : user_token